name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:
  issues: 'write' # To fix the HttpError: Resource not accessible by integration
  pull-requests: 'write' # To fix the HttpError: Resource not accessible by integration
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/auto-assign.yml
